### ISSUE TITLE
Forside teskt

### ISSUE THREAD

**Issue by suzetteglanz** [suzetteglanz/metadatamodul#1]

**Comment by suzetteglanz** [comment]
![metadata_forside](https://cloud.githubusercontent.com/assets/11499988/16872147/43c69d40-4a8b-11e6-9e5c-a446104d302e.png)

**Comment by NicolaiLolansen** [comment]
Hvad skal det her hedde, hvis det ikke skal hedde metadata?

![image](https://cloud.githubusercontent.com/assets/11227437/16978592/eb5ba148-4e5c-11e6-95e9-f43a35096f04.png)

**Comment by suzetteglanz** [comment]
Statistik
