### ISSUE TITLE
Ret Feltoverskrifter

### ISSUE THREAD

**Issue by suzetteglanz** [suzetteglanz/metadatamodul#14]
"Internt på KKkort" - skal hedde "Vises på KKkort (internt)"
"Eksternt på Københavnerkortet" - skal hedde "Vises på Københavnerkortet (eksternt)

**Comment by NicolaiLolansen** [comment]
Rettet, tilføjet "Eksternt på data.kk.dk" -> "Vises på data.kk.dk (eksternt)"
