### ISSUE TITLE
SpatialSuite kobling

### ISSUE THREAD

**Issue by suzetteglanz** [suzetteglanz/metadatamodul#3]

**Comment by NicolaiLolansen** [comment]
Lukker for nu, da mig og Casper mere eller mindre har fået hul igennem.

**Comment by NicolaiLolansen** [comment]
Søger man efter noget med "æ,ø,å" sker der fejl. Skal have konverteret søgestreng til URL formatering før vi sender. Casper skal hjælpe

**Comment by NicolaiLolansen** [comment]
Fixed
