### ISSUE TITLE
Fortide title - Datakatalog

### ISSUE THREAD

**Issue by suzetteglanz** [suzetteglanz/metadatamodul#7]
Ændre/tilføje overskrift "Datakatalog" m.m. Se mugup.

**Comment by suzetteglanz** [comment]
![metadata_forside](https://cloud.githubusercontent.com/assets/11499988/16872160/5be8405e-4a8b-11e6-980d-4893a5ecf681.png)

**Comment by NicolaiLolansen** [comment]
![image](https://cloud.githubusercontent.com/assets/11227437/17015018/1ce95c7a-4f28-11e6-9a9e-af970fee55a3.png)

Så er vi færdige, du må meget gerne komme med kommentarer til forbedringer :+1:
